-- Autenticação de compatibilidade do MES no banco compartilhado.
-- As sessões são efêmeras e não são migradas do ambiente legado.
begin;

set local lock_timeout = 5000;
set local statement_timeout = 60000;

create table if not exists public.usuarios (
    id integer generated by default as identity primary key,
    nome text not null unique,
    senha_hash text not null,
    is_admin integer not null default 0
        check (is_admin in (0, 1))
);

create table if not exists public.sessoes_usuario (
    token text primary key,
    usuario_id integer not null
        references public.usuarios(id) on delete cascade,
    expira_em timestamp with time zone not null
);

create index if not exists sessoes_usuario_usuario_id_idx
    on public.sessoes_usuario(usuario_id);

create index if not exists sessoes_usuario_expira_em_idx
    on public.sessoes_usuario(expira_em);

alter table public.usuarios enable row level security;
alter table public.sessoes_usuario enable row level security;

revoke all on table public.usuarios from anon, authenticated;
revoke all on table public.sessoes_usuario from anon, authenticated;
revoke all on sequence public.usuarios_id_seq from anon, authenticated;

comment on table public.usuarios is
    'Contas de compatibilidade do MES durante a consolidação de autenticação.';

comment on table public.sessoes_usuario is
    'Sessões web efêmeras do MES; não migrar sessões do ambiente legado.';

commit;
