ALTER TABLE IF EXISTS public.skus ALTER COLUMN estoque_minimo DROP NOT NULL;

CREATE TABLE IF NOT EXISTS public.dashboard_movement_cache (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id integer,
    created_at timestamp without time zone NOT NULL,
    usuario_id integer,
    usuario_nome varchar(80),
    sku_id integer,
    sku_codigo varchar(80) NOT NULL,
    descricao varchar(255) NOT NULL,
    tipo varchar(20) NOT NULL,
    quantidade numeric(14, 3) NOT NULL,
    saldo_anterior numeric(14, 3) NOT NULL,
    saldo_posterior numeric(14, 3) NOT NULL,
    documento varchar(120),
    observacao text,
    cached_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dashboard_movement_cache_created_at
    ON public.dashboard_movement_cache (created_at DESC);

CREATE INDEX IF NOT EXISTS ix_dashboard_movement_cache_movement_id
    ON public.dashboard_movement_cache (movement_id);

CREATE INDEX IF NOT EXISTS ix_dashboard_movement_cache_tipo
    ON public.dashboard_movement_cache (tipo);

ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.skus ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.stock_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.label_print_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.dashboard_movement_cache ENABLE ROW LEVEL SECURITY;
